# Generated by Django 5.0.6 on 2025-08-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=500, null=True)),
                ('paragraph', models.TextField(blank=True, max_length=600, null=True)),
                ('image', models.ImageField(upload_to='slider_images/')),
            ],
        ),
    ]
