# Generated by Django 5.1.2 on 2025-06-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='reference_id',
            field=models.CharField(max_length=50),
        ),
    ]
