# Generated by Django 5.1.2 on 2025-06-22 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarysheet',
            name='paid_amount',
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
    ]
