# Generated by Django 5.1.2 on 2025-06-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_salarysheet_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarysheet',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
