# Generated by Django 5.0.6 on 2025-08-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_salarysheet_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarysheet',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('partial', 'partial'), ('paid', 'paid')], default='unpaid', max_length=10),
        ),
    ]
